### ISSUE TITLE
Playable on Linux

### ISSUE THREAD

**Issue by mbndr** [PixieCatSupreme/AnodyneSharp#27]
Hey there, I just discovered this project and I love it. Nice to see that someone does something with the original source code and assets!
I'm a big fan of Anodyne but currently have no Windows (or Mac) machine to play on (have to play on my phone and I'm bad at touch controls...). It really would be nice if this project would be a way to play on Linux.
I don't know much about C# and how platform independent it is and simply tried to build it with `msbuild AnodyneSharp.sln` on my Archlinux but there are a few errors (`MSB3248`, `MSB4236`, `MSB3971`).

Before digging deeper I wanted to ask if there is some code which prevents it from being built on Linux?

**Comment by SephDB** [comment]
We are able to cross-compile from windows to linux(and that build is available in the Releases, but it's from the demo release).

IIRC to build monogame shaders on linux you need Wine. This is a limitation of Monogame. As for the specific build errors, I think you'll need to get us more than just the error numbers.

For the first one, I did find [this](https://issueexplorer.com/issue/godotengine/godot/52581) which indicates it's an issue with Arch's mono package. Seems relevant bc our engine uses reflection in quite a few places to get the code cleaner.

Edit: The other two errors also seem to indicate that your version of .net is too old to build our project.

**Comment by mbndr** [comment]
Thanks, I also read in some places that it's a mess on Arch...I will try again on Ubuntu with Wine (cannot promise to do it this week). Good to see the Linux release, sorry about not looking there!
I thought the same about the dotnet version but as far as I can see the build process wants 5.0 or higher and I have version 6.0.100 installed. Maybe that's another strange Arch thing...

**FYI** the log of the build (`msbuild AnodyneSharp.sln`):
```
Microsoft (R) Build Engine version 16.10.1 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 1/6/2022 11:32:33 AM.
Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (1) is building "/home/maxi/tmp/AnodyneSharp/Fluent-State-Machine/Fluent-State-Machine.csproj" (2) on node 1 (default targets).
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/2.0-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. [/home/maxi/tmp/AnodyneSharp/Fluent-State-Machine/Fluent-State-Machine.csproj]
Done Building Project "/home/maxi/tmp/AnodyneSharp/Fluent-State-Machine/Fluent-State-Machine.csproj" (default targets) -- FAILED.
Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (1) is building "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Windows/AnodyneSharp.Windows.csproj" (3) on node 1 (default targets).
/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Windows/AnodyneSharp.Windows.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.
Done Building Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Windows/AnodyneSharp.Windows.csproj" (default targets) -- FAILED.
Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (1) is building "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Multiplatform/AnodyneSharp.Multiplatform.csproj" (4) on node 1 (default targets).
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Multiplatform/AnodyneSharp.Multiplatform.csproj]
Done Building Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Multiplatform/AnodyneSharp.Multiplatform.csproj" (default targets) -- FAILED.
Done Building Project "/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (default targets) -- FAILED.

Build FAILED.

"/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (default target) (1) ->
"/home/maxi/tmp/AnodyneSharp/Fluent-State-Machine/Fluent-State-Machine.csproj" (default target) (2) ->
(ResolveAssemblyReferences target) -> 
  /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/2.0-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. [/home/maxi/tmp/AnodyneSharp/Fluent-State-Machine/Fluent-State-Machine.csproj]


"/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (default target) (1) ->
"/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Windows/AnodyneSharp.Windows.csproj" (default target) (3) ->
  /home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Windows/AnodyneSharp.Windows.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.


"/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.sln" (default target) (1) ->
"/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Multiplatform/AnodyneSharp.Multiplatform.csproj" (default target) (4) ->
(GetReferenceAssemblyPaths target) -> 
  /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/home/maxi/tmp/AnodyneSharp/AnodyneSharp/AnodyneSharp.Multiplatform/AnodyneSharp.Multiplatform.csproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.03
```

**Edit**: Just playing the first level, you did a damn good job! :1st_place_medal:

**Comment by SephDB** [comment]
One easy fix(but not sufficient to get the whole thing building) is to not build the AnodyneSharp.Windows project, which we probably should remove anyway since there's some weirdness with the shaders and the multiplatform(OpenGL) project works fine on windows as well.

> Edit: Just playing the first level, you did a damn good job! 🥇

Thanks, do note that the project isn't done yet, we're still missing quite a few late-game things, including the credits. If you're playing the demo, that one is complete up to activating windmill(which is also the ending point of the original's demo)
